# -*- coding: utf-8 -*-
"""filter-licitacoes-exploration

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AeXHJe4D8sa0bOGgo0vIxLZjfsMwif5_
"""

#!pip install google-colab-selenium

import requests
from bs4 import BeautifulSoup

url = "https://transparencia.joaopessoa.pb.gov.br/#/licitacoes"
driver = requests.get(url)
soup = BeautifulSoup(driver.content, "html.parser")

print(soup.prettify())

import google_colab_selenium as gs
from bs4 import BeautifulSoup
from selenium.webdriver.common.by import By

url = "https://transparencia.joaopessoa.pb.gov.br/#/licitacoes"
driver = gs.Chrome()
driver.get(url)
#driver.implicitly_wait(10)
soup = BeautifulSoup(driver.page_source, "html.parser")

driver.quit()



print(soup.prettify())

# Secretarias e Orgaos

with open("secretarias-orgaos.html") as fp:
  soup = BeautifulSoup(fp, 'html.parser')

for secretaria in soup.find_all('span', {'class' : 'ng-star-inserted'}):
  print(secretaria.text)

# Participante

with open("participante.html") as fp:
  soup = BeautifulSoup(fp, 'html.parser')

for participante in soup.find_all('span', {'class' : 'ng-star-inserted'}):
  print(participante.text)

# Unidades Interessadas

with open("unidades-interessadas.html") as fp:
  soup = BeautifulSoup(fp, 'html.parser')

for unidades_interessadas in soup.find_all('div', {'class' : 'ng-star-inserted'}):
  print(unidades_interessadas.text)

